locale: "it-IT"
title: Davide Chen # Title of your site
url: "http://yourdomain.com" # the base hostname & protocol for your site
baseurl: "/homepage/" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author details for the jekyll-seo-tag gem
author:
  name: Davide Chen
  email: your-email@domain.com
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Strata Reloaded Template
  links:
    - https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook: https://www.facebook.com/davide.chen.31
  - Google Plus
  - Instagram: https://www.instagram.com/no_problem_zz/
  - LinkedIn: https://www.linkedin.com/in/davide-chen-89aa02145/
  - Github: https://github.com/Grade0
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
